#!/usr/bin/env python3
"""
clean-pema-namgyal.py
Generated by the clean-raw-text skill.
Removes mechanical OCR/segmentation debris from:
  0-INBOX/raw-data/སྒྲོལ་མ་ཉེར་གཅིག/_RCFC0F990 ཕྱག་འཚལ་ཉེར་གཅིག་གི་བསྟོད་འགྲེལ་བདུད་རྩིའི་དགའ་ཚལ་བཞུགས་སོ།།- Segmentation.txt
Output:
  0-INBOX/temp/pema-namgyal/work/cleaned.md
"""
import glob
import re
from pathlib import Path

RAW_DIR = Path("0-INBOX/raw-data/སྒྲོལ་མ་ཉེར་གཅིག")
SOURCE = Path(glob.glob(str(RAW_DIR / "*RCFC0F990*.txt"))[0])
OUTPUT = Path("0-INBOX/temp/pema-namgyal/work/cleaned.md")

NBT = '༌'       # ༌ non-breaking tsheg
STD_TSHEG = '་'  # ་ standard tsheg
SHAD_CHARS = '།༎'

# Specific mid-word space fix confirmed by manual inspection (rule 8):
# a bare space split the single word བདུད ("bdud") into བདུ + ད.
MID_WORD_FIXES = [
    ('བདུ ད་རྩིར', 'བདུད་རྩིར'),
]


def clean(text: str) -> str:
    stats = {'nbt_replacements': 0, 'mid_word_fixes': 0,
             'orphan_joins': 0, 'blank_run_collapses': 0}

    # 1. Strip BOM if present
    text = text.lstrip('﻿')

    # 2. Non-breaking tshegs -> standard tsheg
    stats['nbt_replacements'] = text.count(NBT)
    text = text.replace(NBT, STD_TSHEG)

    # 3. Specific mid-word space fixes
    for bad, good in MID_WORD_FIXES:
        if bad in text:
            stats['mid_word_fixes'] += text.count(bad)
            text = text.replace(bad, good)

    lines = text.split('\n')

    # 4. Group into blank-line-delimited blocks
    blocks = []
    cur = []
    for l in lines:
        if l.strip() == '':
            if cur:
                blocks.append(cur)
                cur = []
        else:
            cur.append(l)
    if cur:
        blocks.append(cur)

    # 5. Within each block, join a line into the next line whenever it does
    #    not end with a sentence-closing shad — this is an orphaned wrap,
    #    not a deliberate verse-line break.
    joined_blocks = []
    for b in blocks:
        out = []
        i = 0
        while i < len(b):
            line = b[i].strip()
            while i + 1 < len(b) and line and not line.endswith(tuple(SHAD_CHARS)):
                stats['orphan_joins'] += 1
                nxt = b[i + 1].strip()
                line = line + nxt
                i += 1
            out.append(line)
            i += 1
        joined_blocks.append(out)

    # 6. Reassemble with a single blank line between blocks
    result = '\n\n'.join('\n'.join(b) for b in joined_blocks) + '\n'

    print(f"Done — NBT replacements: {stats['nbt_replacements']}, "
          f"mid-word space fixes: {stats['mid_word_fixes']}, "
          f"orphan line joins: {stats['orphan_joins']}, "
          f"blocks: {len(joined_blocks)}")
    return result


if __name__ == '__main__':
    text = SOURCE.read_text(encoding='utf-8')
    cleaned = clean(text)
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(cleaned, encoding='utf-8')
    print(f"Written to: {OUTPUT}")
