#!/usr/bin/env python3
"""
clean-tsultrim-namdak.py
Generated by the clean-raw-text skill (invoked via raw-to-sources).
Removes mechanical OCR/scan debris from:
  0-INBOX/temp/wf/c17.txt
  (source book: སྒྲོལ་འགྲེལ་ཚོགས་གཉིས་རྒྱ་མཚོར་འཇུག་པའི་གྲུ་གཟིངས, Khenpo
   Tsultrim Namdak, Palpung Sungrab Partrun Khang, 2008 — a bound anthology
   of five Tara works by this author, per its own དཀར་ཆག: (1) a praise-poem,
   (2) a commentary on the root praise's own commentary, (3) a commentary on
   the 21-praise root text proper, (4) a compiled book of protection-tale
   colophons, (5) a maṇḍala-offering-ritual commentary sharing the book's
   cover title, plus (6) a three-kāya prayer, (7) a treasure-revealed sādhana
   commentary, and (8) a small collection of further Tara praises + the
   printer's colophon.)
Output:
  0-INBOX/temp/tsultrim-namdak/cleaned.md

Profile findings (see conversation record for the full line-by-line audit):
  - total lines: 2978. No UTF-8 BOM, no CRLF line endings.
  - non_breaking_tshegs (U+0F0C ༌): 154 — replaced with standard tsheg (U+0F0B).
  - PAGE MARKERS: 121 bare arabic page-number lines (matching ^\\s*[0-9]+\\s*$,
    e.g. "1".."134") plus 3 bare roman-numeral front-matter page markers
    ("i","ii","iii"). This text is Tibetan and uses Tibetan-script numerals
    (༠-༩) for every genuine in-text number (dates, counts, mantra repeats,
    etc.) — so every ASCII/Arabic digit run in the file is, without
    exception, a digitisation/pagination artifact, never original content.
    The only place Arabic digits are genuine content is the English-language
    publisher's imprint block (phone/fax numbers, print run, ISBN) — handled
    separately below, never touched by the blanket digit-line rule.
  - RUNNING HEADERS: this book prints a running header on every page —
    verso pages carry the whole book's cover title (or, inside the
    ma�NDala-ritual chapter, that chapter's own title), recto pages carry
    the current chapter's own title — immediately following each page-number
    line. Confirmed by tabulating the line immediately after every one of
    the 121 page-number lines: the same handful of strings recur dozens of
    times each (52×, 20×, 9×, 7×, 4×, plus single-syllable-dropped OCR
    variants), unlike any genuine chapter-opening heading, which occurs
    exactly once. Removed every recurring-header occurrence; genuine
    chapter-opening headings (which happen to immediately follow a
    page-number line purely by chance of pagination) are left untouched.
    One exception required manual handling: the printer's colophon chapter
    is titled "སྤར་བྱང་།", and that exact string is *also* used as that
    chapter's own running header on later pages — so the same string is
    both a genuine heading (first occurrence, line 2847) and later pure
    header noise (line 2897). Only the second occurrence is removed.
  - FRONT-MATTER SCAN DUPLICATION (lines 1-69): the book's cover/imprint
    leaf was evidently scanned/OCR'd more than once. Interleaved with a
    library archival stamp (itself OCR'd differently each time: "སལ་སྤུངས་།"
    / "ཐེག་གསུམ་ཆོས་ཕྱིར་༣གོ།" / "549"; "་སལ་༼སྤངས་མཛོད།"; "དསལ་སྤྱངས་མཛེ།" /
    "ཐེག་གསུམ་ཆོས་ཀྱི་འཁོར་ལོ་ཆེ།"; "སལ་སྤངས་ལས་མཛ་་་"; "་སལ་སྤྱངས་མཛོད།" — all
    garbled OCR of a Palpung library shelf-stamp, never part of the printed
    book) are: (a) the cover title/author/publisher block, printed once
    genuinely (lines 4-8) and once more as an exact duplicate (lines 26-30);
    (b) the copyright/imprint page, printed once with clean OCR (lines
    32-46) and once more as a duplicate with markedly worse OCR, cut off
    mid-word (lines 51-65); (c) the one-line dedication caption
    "སྲོལ་མ་ཉེར་གཅིག་ལ་ན་མོ།", printed twice identically (lines 49, 68).
    Kept exactly one clean copy of each; removed the stamps and the
    duplicate/degraded repeats. The "names of the 21 Tāras" decorative
    plate (lines 11-22) is not duplicated and is left untouched.
  - TOC PAGE-NUMBER BLEED (lines 145-165, the book's own དཀར་ཆག/table of
    contents): the 2-column title/page-number layout was OCR'd as
    interleaved text, producing page numbers fused onto the start or end of
    entry-title lines ("47ཕྱོགས་...", "...བ་དན 1", "63གྲུ་...", etc.) and two
    page numbers standing alone ("109","131" — already covered by the
    blanket page-marker rule). Stripped the fused digit runs, leaving every
    TOC entry's title text intact and unreordered.
  - One further isolated case of the same bleed inside the body text itself:
    line 2440 ends "...གོ་འཕང་ཐོབ་པའི་རྒྱུར་གྱུར་ཅིག། 11" immediately before
    the page-number line "105" — the trailing " 11" is the same class of
    page-marker bleed (this text uses Tibetan, not Arabic, numerals for any
    genuine content), stripped; the verse itself is untouched.
  - mid_word_spaces: not touched. A regex scan for
    "<Tibetan char><space><Tibetan char>" finds ~1980 raw hits, the large
    majority immediately adjacent to a shad (legitimate sentence-final
    punctuation spacing, not a mid-word break). Restricting to non-shad-
    adjacent pairs still leaves ~250 candidates, dominated by decorative
    gter-tsheg (༔) and close-parenthesis (༽) boundaries — both legitimate
    word/clause-boundary punctuation in this ritual/praise material, not
    PDF-justification artefacts. Given the volume and the absence of a
    reliable mechanical discriminator, and following this batch's own
    precedent (see 0-INBOX/temp/tenzin-dhonzang/clean-tenzin-dhonzang.py,
    which hand-checked its far smaller candidate set and altered none of
    them), no mid-word-space collapsing was applied here. Flagged for a
    human contributor's review rather than guessed at scale.
  - orphaned_line_fragments: none of the file's short (<=15 char) lines are
    OCR-severed fragments — they are complete decorative/mantra elements
    ("ཨཙམད", "པདྨ", "ཨོ", "ཉམཿ", etc., a seed-syllable dhāraṇī block, lines
    ~2941-2953) or complete short verse cola — none joined.
  - blank-line runs: normalised to a single blank line between paragraphs.
"""
import re
from pathlib import Path

SOURCE = Path("0-INBOX/temp/wf/c17.txt")
OUTPUT = Path("0-INBOX/temp/tsultrim-namdak/cleaned.md")

NBT = '༌'        # non-breaking tsheg ༌
STD_TSHEG = '་'  # standard tsheg ་

PAGE_NUM_LINE = re.compile(r'^\s*[0-9]+\s*$')
ROMAN_NUM_LINE = re.compile(r'^\s*[ivxIVX]+\s*$')

# --- Front-matter surgery (1-indexed source line numbers; see docstring) ---
# Library archival stamp lines (garbled OCR of a Palpung shelf-mark, never
# part of the printed book).
STAMP_LINES = {1, 2, 3, 10, 24, 25, 48, 67}
# Duplicate cover-title block (exact repeat of lines 4-8).
DUP_COVER_BLOCK = set(range(26, 31))  # 26-30
# Duplicate, more-degraded copyright/imprint block (repeat of lines 32-46).
DUP_IMPRINT_BLOCK = set(range(51, 66))  # 51-65
# Second, duplicate occurrence of the one-line dedication caption
# (first occurrence at line 49 is kept).
DUP_DEDICATION_LINE = {68}

FRONT_MATTER_REMOVE = STAMP_LINES | DUP_COVER_BLOCK | DUP_IMPRINT_BLOCK | DUP_DEDICATION_LINE

# --- TOC page-number-bleed fixes (1-indexed source line numbers) ---
# (line_no, regex_to_strip)
TOC_LEADING_DIGITS = {154, 157, 161, 162}   # strip leading digit run
TOC_TRAILING_DIGITS = {147, 149, 151}       # strip trailing " <digits>"
LEADING_DIGITS_RE = re.compile(r'^[0-9]+')
TRAILING_DIGITS_RE = re.compile(r'\s+[0-9]+\s*$')

# Isolated body-text page-number bleed (see docstring).
BODY_TRAILING_DIGITS = {2440}

# --- Running-header canonical forms (normalised: trailing punctuation and
# whitespace stripped) — removed wherever they recur as a running header.
RUNNING_HEADERS = {
    "ཚོགས་གཉིས་རྒྱ་མཚོར་འཇུག་པའི་གྲུ་གཟིངས",
    "ཚོགས་གཉིས་རྒྱ་མཚོར་འཇུག་པའི་གཟིངས",  # OCR variant, one syllable dropped
    "སྒྲོལ་མའི་བསྟོད་འགྲེལ་འཕགས་མའི་བྱིན་རླབས་འགུགས་པའི་ལྕགས་ཀྱུ",
    "འཇིགས་པ་ལས་བསྐྱབས་པའི་གཏམ་དད་པའི་རྔ་སྒྲ",
    "བསྟོད་འགྲེལ་འདོད་རྒུའི་ཕྲིན་ལས་དཔལ་སྟེར",
    "མཎྜལ་བཞི་ཆོག་འགྲེལ་པ་ཚོགས་གཉིས་རྒྱ་མཚོར་འཇུག་པའི་གྲུ་གཟིངས",
    "སྒྲོལ་བསྟོད་ཁག",
}
# Only apply the canonical-header removal from here on (well past the
# front-matter surgery region and the TOC, so no chance of colliding with
# either).
HEADER_RULE_ACTIVE_FROM_LINE = 190

# The colophon chapter's heading text ("སྤར་བྱང་།") doubles as its own later
# running header. Keep the first (genuine heading) occurrence, remove the
# rest.
DUAL_PURPOSE_HEADER = "སྤར་བྱང"


def normalise_header(s: str) -> str:
    return s.strip().rstrip('།.༎༏་ ')


def clean(text: str) -> str:
    lines = text.split('\n')
    stats = {
        'nbt_replacements': 0,
        'stamp_lines_removed': 0,
        'dup_cover_block_removed': 0,
        'dup_imprint_block_removed': 0,
        'dup_dedication_removed': 0,
        'toc_digit_fixes': 0,
        'body_digit_bleed_fixes': 0,
        'page_number_lines_removed': 0,
        'roman_number_lines_removed': 0,
        'running_header_lines_removed': 0,
    }

    out = []
    seen_dual_purpose_header = False

    for idx, line in enumerate(lines):
        line_no = idx + 1  # 1-indexed, matches source line numbers used above

        # 1. Front-matter surgery: drop stamp lines / duplicate blocks outright.
        if line_no in FRONT_MATTER_REMOVE:
            if line_no in STAMP_LINES:
                stats['stamp_lines_removed'] += 1
            elif line_no in DUP_COVER_BLOCK:
                stats['dup_cover_block_removed'] += 1
            elif line_no in DUP_IMPRINT_BLOCK:
                stats['dup_imprint_block_removed'] += 1
            elif line_no in DUP_DEDICATION_LINE:
                stats['dup_dedication_removed'] += 1
            continue

        # 2. Non-breaking tsheg -> standard tsheg (safe everywhere).
        if NBT in line:
            stats['nbt_replacements'] += line.count(NBT)
            line = line.replace(NBT, STD_TSHEG)

        # 3. TOC page-number bleed.
        if line_no in TOC_LEADING_DIGITS:
            new_line = LEADING_DIGITS_RE.sub('', line)
            if new_line != line:
                stats['toc_digit_fixes'] += 1
            line = new_line
        if line_no in TOC_TRAILING_DIGITS:
            new_line = TRAILING_DIGITS_RE.sub('', line)
            if new_line != line:
                stats['toc_digit_fixes'] += 1
            line = new_line

        # 4. Isolated body page-number bleed.
        if line_no in BODY_TRAILING_DIGITS:
            new_line = TRAILING_DIGITS_RE.sub('', line)
            if new_line != line:
                stats['body_digit_bleed_fixes'] += 1
            line = new_line

        # 5. Blanket page-marker removal (arabic and roman numeral lines).
        if PAGE_NUM_LINE.match(line):
            stats['page_number_lines_removed'] += 1
            continue
        if ROMAN_NUM_LINE.match(line):
            stats['roman_number_lines_removed'] += 1
            continue

        # 6. Running-header removal.
        if line_no >= HEADER_RULE_ACTIVE_FROM_LINE:
            norm = normalise_header(line)
            if norm in RUNNING_HEADERS:
                stats['running_header_lines_removed'] += 1
                continue
            if norm.startswith(DUAL_PURPOSE_HEADER) and len(norm) <= len(DUAL_PURPOSE_HEADER) + 2:
                if seen_dual_purpose_header:
                    stats['running_header_lines_removed'] += 1
                    continue
                seen_dual_purpose_header = True

        out.append(line)

    result = '\n'.join(out)
    # Trim trailing whitespace on each line.
    result = '\n'.join(l.rstrip() for l in result.split('\n'))
    # Normalise blank lines: collapse runs of 2+ blank lines into exactly one.
    result = re.sub(r'\n{3,}', '\n\n', result)
    # Trim leading/trailing blank lines, ensure single trailing newline.
    result = result.strip('\n') + '\n'

    print("Done —")
    for k, v in stats.items():
        print(f"  {k}: {v}")
    return result


if __name__ == '__main__':
    raw = SOURCE.read_text(encoding='utf-8')
    cleaned = clean(raw)
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(cleaned, encoding='utf-8')
    print(f"Written to: {OUTPUT}")
