#!/usr/bin/env python3
"""
clean-drakpa-gyaltsen.py
Generated by the clean-raw-text skill.
Removes mechanical OCR/PDF debris from:
  0-INBOX/raw-data/སྒྲོལ་མ་ཉེར་གཅིག/R1FAE45EC སྒྲོལ་མ་ཕྱག་འཚལ་ཉི་ཤུ་རྩ་གཅིག་གི་བསྟོད་པའི་རྣམ་བཤད་གསལ་བའི་འོད་ཟེར་ཞེས་བྱ་བ་བཞུགས་སོ།-segmentation.txt
Output:
  0-INBOX/temp/drakpa-gyaltsen/cleaned.md

Profile findings (see conversation):
  - page_markers: 0
  - running_headers: none genuine — the recurring "ཞེས་པ་ནི།" / "ནི་" lines are
    the text's own formulaic glossing marker ("this means:"), not a page
    header/footer. Not removed.
  - mid_word_spaces: 0 genuine — the naive scan's candidates are all normal
    word/clause boundaries (e.g. "དྲུག གསང་" enumerating six items, "སློབ་དཔོན
    འཕགས་པ་" = "the master, Ārya [Nāgārjuna]"). Not touched.
  - non_breaking_tshegs (U+0F0C): 13 occurrences — replaced with standard
    tsheg (U+0F0B).
  - BOM (U+FEFF) at the very start of the file — stripped.
  - orphaned_line_fragments: none — the file's short lines (root-verse
    phrase / "ཞེས་པ་ནི།" marker / gloss) are the transcriber's own
    segmentation structure, preserved as-is per raw-to-sources.
"""
import re
from pathlib import Path

SOURCE = Path("0-INBOX/raw-data/སྒྲོལ་མ་ཉེར་གཅིག/R1FAE45EC སྒྲོལ་མ་ཕྱག་འཚལ་ཉི་ཤུ་རྩ་གཅིག་གི་བསྟོད་པའི་རྣམ་བཤད་གསལ་བའི་འོད་ཟེར་ཞེས་བྱ་བ་བཞུགས་སོ།-segmentation.txt")
OUTPUT = Path("0-INBOX/temp/drakpa-gyaltsen/cleaned.md")

NBT = '༌'  # ༌ non-breaking tsheg
STD_TSHEG = '་'  # ་ standard tsheg
BOM = '﻿'

def clean(text: str) -> str:
    stats = {'bom_removed': 0, 'nbt_replacements': 0}

    if text.startswith(BOM):
        text = text[len(BOM):]
        stats['bom_removed'] = 1
    # BOM can also reappear at the start of lines after a line break in this file
    n_bom_inline = text.count(BOM)
    if n_bom_inline:
        text = text.replace(BOM, '')
        stats['bom_removed'] += n_bom_inline

    stats['nbt_replacements'] = text.count(NBT)
    text = text.replace(NBT, STD_TSHEG)

    # Strip trailing whitespace on each line (mechanical, no content change)
    lines = [l.rstrip() for l in text.split('\n')]

    # Normalise blank lines: collapse runs of more than one blank line into one
    result_lines = []
    for l in lines:
        if l == '' and result_lines and result_lines[-1] == '':
            continue
        result_lines.append(l)
    result = '\n'.join(result_lines)

    print(f"Done — BOM chars removed: {stats['bom_removed']}, "
          f"NBT replacements: {stats['nbt_replacements']}")
    return result

if __name__ == '__main__':
    text = SOURCE.read_text(encoding='utf-8')
    cleaned = clean(text)
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(cleaned, encoding='utf-8')
    print(f"Written to: {OUTPUT}")
