#!/usr/bin/env python3
"""
clean-tenga-tulku.py
Generated by the clean-raw-text skill.
Removes mechanical OCR/PDF/transcription debris from:
  0-INBOX/raw-data/སྒྲོལ་མ་ཉེར་གཅིག/R4C616099 ཕྱག་འཚལ་ཉེར་གཅིག་གི་ཕན་ཡོན་དང་བཅས་པ་གསལ་བའི་མེ་ལོང་ཞེས་བྱ་བ་བཞུགས་སོ།། །། B-2-Segnementation.txt
Output:
  0-INBOX/temp/tenga-tulku/cleaned.md
"""
import re
from pathlib import Path

SOURCE = Path("0-INBOX/raw-data/སྒྲོལ་མ་ཉེར་གཅིག/R4C616099 ཕྱག་འཚལ་ཉེར་གཅིག་གི་ཕན་ཡོན་དང་བཅས་པ་གསལ་བའི་མེ་ལོང་ཞེས་བྱ་བ་བཞུགས་སོ།། །། B-2-Segnementation.txt")
OUTPUT = Path("0-INBOX/temp/tenga-tulku/cleaned.md")

NBT       = '༌'  # ༌ non-breaking tsheg
STD_TSHEG = '་'  # ་ standard tsheg

def clean(text: str) -> str:
    stats = {'nbt_replacements': 0, 'trailing_ws_lines': 0, 'blank_run_collapses': 0}

    # Normalise line endings
    text = text.replace('\r\n', '\n').replace('\r', '\n')

    lines = text.split('\n')
    out = []
    for line in lines:
        # Non-breaking tshegs -> standard tsheg
        if NBT in line:
            stats['nbt_replacements'] += line.count(NBT)
            line = line.replace(NBT, STD_TSHEG)
        # Trailing whitespace
        stripped_line = line.rstrip()
        if stripped_line != line:
            stats['trailing_ws_lines'] += 1
            line = stripped_line
        out.append(line)

    result = '\n'.join(out)

    # Collapse runs of more than one blank line into a single blank line
    def _collapse(m):
        stats['blank_run_collapses'] += 1
        return '\n\n'
    result = re.sub(r'\n{3,}', _collapse, result)

    print(f"Done — NBT replacements: {stats['nbt_replacements']}, "
          f"trailing-whitespace lines trimmed: {stats['trailing_ws_lines']}, "
          f"blank-line runs collapsed: {stats['blank_run_collapses']}")
    return result

if __name__ == '__main__':
    text = SOURCE.read_text(encoding='utf-8-sig')  # utf-8-sig strips a leading BOM
    cleaned = clean(text)
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(cleaned, encoding='utf-8')
    print(f"Written to: {OUTPUT}")
