#!/usr/bin/env python3
"""
clean-sangye-nyentrul.py
Generated by the clean-raw-text skill.
Removes mechanical debris (non-breaking tshegs, redundant blank-line runs)
from:
  0-INBOX/raw-data/སྒྲོལ་མ་ཉེར་གཅིག/R49348A41 རྗེ་བཙུན་མ་འཕགས་མ་སྒྲོལ་མ་ཉི་ཤུ་རྩ་གཅིག་གི་ཚིག་འགྲེལ་དང་དམིགས་རིམ་ཉུང་ངུར་བཀོད་པ་འཕགས་མའི་བྱིན་རླབས་གྲུ་ཆར་བཞུགས།།-Segmentation.txt
Output:
  0-INBOX/temp/sangye-nyentrul/cleaned.md

Profile (against the 391-line raw file):
  - page markers: 0
  - running headers/footers: 0 (the 20x-repeated "ཞེས་པ་ལ།" is substantive
    section-transition text, not a header/footer — left untouched)
  - non-breaking tshegs (U+0F0C): 14
  - blank-line runs of 3+ newlines (double-blank paragraph separators): 96
  - candidate mid-word spaces: on inspection these are all either Tibetan
    numeral list markers ("༡ ཕྱག་...", "༡༠ འཆབ་...") followed by a normal
    space, or isolated missing-tsheg spots in the source transcription
    itself (e.g. "སྐུ་མདོག་དམར་ནག པད་ཟླའི") — none are PDF-justification
    artifacts, so none are altered (never fix spelling/punctuation per
    clean-raw-text Rule 2).
"""
import re
from pathlib import Path

SOURCE = Path("/Users/tashitsering/Desktop/work/Obsidian/21-taras-rails/0-INBOX/raw-data/སྒྲོལ་མ་ཉེར་གཅིག/R49348A41 རྗེ་བཙུན་མ་འཕགས་མ་སྒྲོལ་མ་ཉི་ཤུ་རྩ་གཅིག་གི་ཚིག་འགྲེལ་དང་དམིགས་རིམ་ཉུང་ངུར་བཀོད་པ་འཕགས་མའི་བྱིན་རླབས་གྲུ་ཆར་བཞུགས།།-Segmentation.txt")
OUTPUT = Path("/Users/tashitsering/Desktop/work/Obsidian/21-taras-rails/0-INBOX/temp/sangye-nyentrul/cleaned.md")

NBT = '༌'       # ༌ non-breaking tsheg
STD_TSHEG = '་'  # ་ standard tsheg

def clean(text: str) -> str:
    stats = {'nbt_replacements': text.count(NBT)}
    text = text.replace(NBT, STD_TSHEG)

    # Normalise runs of blank lines (3+ consecutive newlines -> single blank line)
    result = re.sub(r'\n{3,}', '\n\n', text)

    print(f"Done — NBT replacements: {stats['nbt_replacements']}")
    return result

if __name__ == '__main__':
    text = SOURCE.read_text(encoding='utf-8')
    cleaned = clean(text)
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(cleaned, encoding='utf-8')
    print(f"Written to: {OUTPUT}")
