#!/usr/bin/env python3
"""
clean-gendun-gyatso.py
Generated by the clean-raw-text skill (invoked via raw-to-sources).
Removes mechanical OCR/PDF debris from:
  0-INBOX/raw-data/སྒྲོལ་མ་ཉེར་གཅིག/RA706B3B9 ཕྱག་འཚལ་སྒྲོལ་མ་ཉེར་གཅིག་མའི་རྣམ་བཤད།༼ཤ༽ -Segmentation.txt
Output:
  0-INBOX/temp/gendun-gyatso/work/cleaned.md

Profile (see conversation): no page markers, no repeated running
headers/footers (short single-file commentary). Issues found:
  - 1 UTF-8 BOM at file start
  - 10 non-breaking tshegs (U+0F0C ༌)
  - 42 lines with trailing whitespace
  - 17 lines with internal runs of 2+ spaces
  - runs of 2 blank lines between paragraphs throughout (segmenter's own
    paragraph-break convention) -> normalised to a single blank line
Segmentation index numbers embedded in the body (e.g. "2 ...", "12  ...")
are the human transcriber's own paragraph numbering and are preserved
verbatim as content, not treated as page-marker debris.
"""
import re
from pathlib import Path

SOURCE = Path("/Users/tashitsering/Desktop/work/Obsidian/21-taras-rails/0-INBOX/raw-data/སྒྲོལ་མ་ཉེར་གཅིག/RA706B3B9\xa0ཕྱག་འཚལ་སྒྲོལ་མ་ཉེར་གཅིག་མའི་རྣམ་བཤད།༼ཤ༽ -Segmentation.txt")
OUTPUT = Path("/Users/tashitsering/Desktop/work/Obsidian/21-taras-rails/0-INBOX/temp/gendun-gyatso/work/cleaned.md")

NBT = '༌'       # ༌ non-breaking tsheg
STD_TSHEG = '་' # ་ standard tsheg
TIB_RANGE = re.compile(r'[ༀ-࿿]')
MID_SPACE = re.compile(r'([ༀ-࿿]) +([ༀ-࿿])')

def clean(text: str) -> str:
    stats = {'bom': 0, 'nbt_replacements': 0, 'trailing_ws': 0, 'space_runs': 0}

    # 1. Strip UTF-8 BOM if present
    if text.startswith('﻿'):
        text = text[1:]
        stats['bom'] = 1

    lines = text.split('\n')
    out = []
    for line in lines:
        orig = line

        # 2. Non-breaking tshegs -> standard tsheg
        if NBT in line:
            stats['nbt_replacements'] += line.count(NBT)
            line = line.replace(NBT, STD_TSHEG)

        # 3. Collapse internal runs of 2+ spaces (between script chars,
        #    around numerals, etc.) to a single space
        new_line, n = re.subn(r'  +', ' ', line)
        if n:
            stats['space_runs'] += n
        line = new_line

        # 4. Strip trailing whitespace
        stripped = line.rstrip(' \t')
        if stripped != line:
            stats['trailing_ws'] += 1
        line = stripped

        out.append(line)

    # 5. Normalise blank lines: collapse runs of 2+ blank lines to exactly one
    result = re.sub(r'\n{3,}', '\n\n', '\n'.join(out))

    print(f"Done — BOM stripped: {stats['bom']}, "
          f"NBT replacements: {stats['nbt_replacements']}, "
          f"trailing-whitespace lines cleaned: {stats['trailing_ws']}, "
          f"internal space-run collapses: {stats['space_runs']}")
    return result

if __name__ == '__main__':
    text = SOURCE.read_text(encoding='utf-8')
    cleaned = clean(text)
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(cleaned, encoding='utf-8')
    print(f"Written to: {OUTPUT}")
