#!/usr/bin/env python3
"""
clean-anon-trinle-char.py
Generated by the clean-raw-text skill (invoked via raw-to-sources).
Removes mechanical OCR/PDF debris from:
  0-INBOX/raw-data/སྒྲོལ་མ་ཉེར་གཅིག/RAF75A533 སྒྲོལ་མའི་འགྲེལ་བ་འཕྲིན་ལས་ཆར་དུ་སྙིལ་བའི་སྤྲིན་ཕུང་། Segmentation - corrected.txt
Output:
  0-INBOX/temp/anon-trinle-char/cleaned.md
"""
import re
from pathlib import Path

SOURCE = Path("0-INBOX/raw-data/སྒྲོལ་མ་ཉེར་གཅིག/RAF75A533 སྒྲོལ་མའི་འགྲེལ་བ་འཕྲིན་ལས་ཆར་དུ་སྙིལ་བའི་སྤྲིན་ཕུང་། Segmentation - corrected.txt")
OUTPUT = Path("0-INBOX/temp/anon-trinle-char/cleaned.md")

NBT = '༌'       # non-breaking tsheg
STD_TSHEG = '་'  # standard tsheg

def clean(text: str) -> str:
    lines = text.split('\n')
    out = []
    stats = {'nbt_replacements': 0, 'trailing_ws_trimmed': 0, 'double_space_collapsed': 0}

    for line in lines:
        # 1. Non-breaking tshegs -> standard tsheg
        if NBT in line:
            stats['nbt_replacements'] += line.count(NBT)
            line = line.replace(NBT, STD_TSHEG)

        # 2. Collapse internal double (or more) spaces to a single space
        new_line, n = re.subn(r'  +', ' ', line)
        stats['double_space_collapsed'] += n
        line = new_line

        # 3. Trim trailing whitespace
        stripped = line.rstrip()
        if stripped != line:
            stats['trailing_ws_trimmed'] += 1
        line = stripped

        out.append(line)

    # 4. Normalise blank-line runs: collapse 2+ consecutive blank lines to exactly 1
    result = re.sub(r'\n{3,}', '\n\n', '\n'.join(out))

    print(f"Done — NBT replacements: {stats['nbt_replacements']}, "
          f"double-spaces collapsed: {stats['double_space_collapsed']}, "
          f"trailing-whitespace lines trimmed: {stats['trailing_ws_trimmed']}")
    return result

if __name__ == '__main__':
    text = SOURCE.read_text(encoding='utf-8')
    cleaned = clean(text)
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(cleaned, encoding='utf-8')
    print(f"Written to: {OUTPUT}")
