#!/usr/bin/env python3
"""
clean-palden-sherab.py
Generated by the clean-raw-text skill (invoked from raw-to-sources).
Removes mechanical OCR/encoding debris from:
  0-INBOX/raw-data/སྒྲོལ་མ་ཉེར་གཅིག/RCD486DE1 རྗེ་བཙུན་སྒྲོལ་མའི་བསྟོད་པ་ཉི་ཤུ་རྩ་གཅིག་གི་ཚིག་དོན་རྣམ་པར་འགྲེལ་བ་དད་བརྩོན་བྱང་ཆུབ་སེམས་མཆོག་གི་པདྨའི་གཞོན་ནུ་ཁ་འབྱེད་པའི་ཐབས་ཤེས་ཉི་ཟླའི་འཛུམ་རླབས་ཞེས་བྱ་བཞུགས་སོ།-Segmentation.txt
Output:
  0-INBOX/temp/palden-sherab/cleaned.md

Profile findings (see conversation record):
  - page_markers: 0
  - running_headers: 1 line repeats >5 times ("ཞེས་གསུངས་ཏེ།", x21) — this is the
    substantive recurring closing phrase after each root-verse quotation, not a
    header/footer; left untouched
  - zero_width_spaces (U+200B): 0
  - BOM (U+FEFF): 1, at file start — stripped
  - non_breaking_tshegs (U+0F0C): 0
  - space-between-Tibetan-char matches: 23 found, all inspected in context by hand;
    every one is a genuine word/pada boundary (a verse-final syllable such as
    དག/གོ/འཇུག/ཤོག/ཅིག/དྲུག immediately before a numeral or the next clause,
    with the tsheg simply omitted) — none splits a single word in half, so no
    mid-word fix was applied (contrast the taranatha commentary, which had one
    genuine split-word case)
  - orphaned line fragments: none found
  - blank-line runs: paragraphs are separated by 2 or 4 blank lines throughout;
    normalised to a single blank line per the output-format spec
"""
import re
from pathlib import Path

SOURCE = Path("0-INBOX/raw-data/སྒྲོལ་མ་ཉེར་གཅིག/RCD486DE1 རྗེ་བཙུན་སྒྲོལ་མའི་བསྟོད་པ་ཉི་ཤུ་རྩ་གཅིག་གི་ཚིག་དོན་རྣམ་པར་འགྲེལ་བ་དད་བརྩོན་བྱང་ཆུབ་སེམས་མཆོག་གི་པདྨའི་གཞོན་ནུ་ཁ་འབྱེད་པའི་ཐབས་ཤེས་ཉི་ཟླའི་འཛུམ་རླབས་ཞེས་བྱ་བཞུགས་སོ།-Segmentation.txt")
OUTPUT = Path("0-INBOX/temp/palden-sherab/cleaned.md")

BOM  = '﻿'  # zero width no-break space / BOM
ZWSP = '​'  # zero width space


def clean(text: str) -> str:
    stats = {'bom': 0, 'zwsp': 0, 'blank_run_collapses': 0}

    if text.startswith(BOM):
        text = text[1:]
        stats['bom'] += 1

    stats['zwsp'] = text.count(ZWSP)
    text = text.replace(ZWSP, '')

    # Normalise blank lines: collapse any run of 2+ blank lines into exactly one.
    before = text
    text = re.sub(r'\n{3,}', '\n\n', text)
    stats['blank_run_collapses'] = before.count('\n\n\n')

    # Trim leading/trailing blank lines, ensure single trailing newline.
    text = text.strip('\n') + '\n'

    print(f"Done — BOM stripped: {stats['bom']}, ZWSP removed: {stats['zwsp']}, "
          f"blank-line runs collapsed: {stats['blank_run_collapses']}")
    return text


if __name__ == '__main__':
    raw = SOURCE.read_text(encoding='utf-8')
    cleaned = clean(raw)
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(cleaned, encoding='utf-8')
    print(f"Written to: {OUTPUT}")
