#!/usr/bin/env python3
"""
clean-konchok-thabkhe.py
Generated by the clean-raw-text skill.
Removes mechanical OCR/encoding debris from:
  0-INBOX/raw-data/སྒྲོལ་མ་ཉེར་གཅིག/R83354184༄༅། ། ཕྱག་འཚལ་ཉེར་གཅིག་མའི་ཊིཀྐ་འཕགས་མའི་ཞལ་ལུང་ཞེས་བྱ་བ་བཞུགས་སོ། -Segmentation.txt
Output:
  0-INBOX/temp/konchok-thabkhe/cleaned.md

Profile findings acted on:
  - leading UTF-8 BOM: 1 (stripped)
  - non-breaking tshegs (U+0F0C ༌): 5 (replaced with standard tsheg ་ U+0F0B)
  - duplicate tshegs ("་་"): 4 (collapsed to a single tsheg)
  - blank-line runs (2+): 122 (normalised to a single blank line)

Profile findings NOT acted on (inspected, judged not to be debris):
  - "གྲུབ་ཆེན་གྱིས།" recurs 7 times but is substantive quote-introducer
    text, not a running header/footer.
  - 5 candidate mid-word spaces (mantra syllables "ཨོཾ་ཨཱཿ ཧཱུྃ", clause
    breaks with a missing shad) do not split a single word — left as-is.
  - Short lines (<=15 chars) are legitimate verse-quote introducers
    ("ཞེས་གསུངས་པ་ལྟར།" etc.), not orphaned OCR fragments — left as-is.
  - The raw transcriber's inline numeric segmentation markers (1, 2, 3...)
    are original content, preserved as-is per raw-to-sources skill.
"""
import re
from pathlib import Path

SOURCE = Path("0-INBOX/raw-data/སྒྲོལ་མ་ཉེར་གཅིག/R83354184༄༅། ། ཕྱག་འཚལ་ཉེར་གཅིག་མའི་ཊིཀྐ་འཕགས་མའི་ཞལ་ལུང་ཞེས་བྱ་བ་བཞུགས་སོ། -Segmentation.txt")
OUTPUT = Path("0-INBOX/temp/konchok-thabkhe/cleaned.md")

NBT       = '༌'  # ༌ non-breaking tsheg
STD_TSHEG = '་'  # ་ standard tsheg
DOUBLE_TSHEG = re.compile('་{2,}')

def clean(text: str) -> str:
    stats = {'bom_stripped': 0, 'nbt_replacements': 0,
             'duplicate_tsheg_collapses': 0, 'blank_run_normalisations': 0}

    # 1. Strip leading BOM
    if text.startswith('﻿'):
        text = text.lstrip('﻿')
        stats['bom_stripped'] = 1

    # 2. Non-breaking tshegs -> standard tsheg
    stats['nbt_replacements'] = text.count(NBT)
    text = text.replace(NBT, STD_TSHEG)

    # 3. Duplicate tshegs -> single tsheg
    def _collapse(m):
        return STD_TSHEG
    text, n = DOUBLE_TSHEG.subn(_collapse, text)
    stats['duplicate_tsheg_collapses'] = n

    # 4. Normalise blank-line runs (2+ blank lines -> 1 blank line)
    text, n2 = re.subn(r'\n{3,}', '\n\n', text)
    stats['blank_run_normalisations'] = n2

    print(f"Done — BOM stripped: {stats['bom_stripped']}, "
          f"NBT replacements: {stats['nbt_replacements']}, "
          f"duplicate-tsheg collapses: {stats['duplicate_tsheg_collapses']}, "
          f"blank-line-run normalisations: {stats['blank_run_normalisations']}")
    return text

if __name__ == '__main__':
    text = SOURCE.read_text(encoding='utf-8')
    cleaned = clean(text)
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(cleaned, encoding='utf-8')
    print(f"Written to: {OUTPUT}")
