#!/usr/bin/env python3
"""
clean-tenzin-dhonzang.py
Generated by the clean-raw-text skill (invoked via raw-to-sources).
Removes mechanical OCR/transcription debris from:
  0-INBOX/raw-data/སྒྲོལ་མ་ཉེར་གཅིག/R3C5D7E26 སྒྲོལ་མ་ཉེར་གཅིག་གི་བསྟོད་འགྲེལ་སྙིང་གི་ནོར་བུ 10-Segnmentation.txt
Output:
  0-INBOX/temp/tenzin-dhonzang/cleaned.md

Profile findings (see conversation record):
  - total lines: 1253; CRLF line terminators throughout; UTF-8 BOM at file start.
  - page_markers: 0 (no "-N-" style page markers found)
  - running_headers: 0 standalone repeats — the 3 lines repeating >5 times
    ("ཞེས་གསུངས།" x11, "ཞེས་དང༌།" x10, "ཅེས་གསུངས།" x7) are the commentary's
    own recurring quotation-closing formula ("thus it is said" / "and:"),
    substantive text — left untouched.
  - digit-prefixed lines (e.g. "1 ...", "43 ...") are the transcriber's own
    line-numbered segmentation markers documented in the raw filename
    ("10-Segnmentation.txt") — original structure, preserved as-is per
    raw-to-sources rule 6 (not block IDs, not touched here).
  - non_breaking_tshegs (U+0F0C ༌): 220 — replaced with standard tsheg (U+0F0B).
  - mid_word_spaces: 22 raw regex hits, all hand-checked — every one is a
    genuine word/clause boundary without a preceding shad (e.g. repeated
    imperative "སོངས་ཤིག སོངས་ཤིག" in the pāramitā-mantra gloss at line 379,
    numbered list items "༡ གཟུགས་དང་། ༢ འཁོར་གཡོག་" at line 509), not an
    OCR-inserted mid-syllable break — none altered.
  - orphaned_line_fragments: the file's short lines (≤15 chars) are all
    complete quotation-introducing/closing formulas ending in a Tibetan
    sentence-final particle ("ཞེས་དང་།", "ཇོ་བོའི་ཞལ་ནས།", "མདོ་ལས།") — not
    OCR-severed fragments — none joined.
  - RUNNING-HEADER BLEED (hand-verified, 2 occurrences): the commentary's own
    title string "སྒྲོལ་མ་ཉེར་གཅིག་གི་བསྟོད་འགྲེལ་སྙིང་གི་ནོར་བུ" (correctly
    present once, legitimately, as the opening title on line 1) reappears
    twice more, fused mid-word into unrelated sentences, in a way that
    breaks the surrounding grammar/orthography:
      * line 134: "...སྐྱུག་མེར་མེར་རམ། ཞེ་[TITLE]། མེར་མེར།..." — removing
        the fused title (plus its own trailing shad and the following space)
        restores "ཞེ་མེར་མེར།", parallel to the list's other onomatopoeic
        vomiting-descriptions ("སྐྱུག་ཏིང་ཏིང་ངམ།", "སྐྱུག་ལོག་ལོག་བྱེད་པ།").
      * line 1236: "...མཁའ་འགྲོའི། ནམ་གྲུལ[TITLE]་གྱི། གཤིན་རྗེའི།..." —
        removing the fused title restores "ནམ་གྲུལ་གྱི།", matching the
        list's own repeating "<demon-class>་གྱི།/འི།" enumeration pattern.
    This is the same class of artifact as a running page header bleeding
    into body text at a page break (cf. the fused page-number artifacts
    documented in 0-INBOX/temp/gendun-drub/clean-gendun-drub.py), just
    carrying the title instead of a number. Both fixes are targeted,
    hand-verified string replacements — not a blanket regex — per the
    no-loss/no-interpretation invariant.
  - blank-line runs: paragraphs are separated by exactly two blank lines
    throughout (one run of four blank lines found once, at the material
    following "རྫོགས་ཚིག་ཡིན་ནོ། །") — normalised to a single blank line
    per the output-format spec.
"""
import re
from pathlib import Path

SOURCE = Path("0-INBOX/raw-data/སྒྲོལ་མ་ཉེར་གཅིག/R3C5D7E26 སྒྲོལ་མ་ཉེར་གཅིག་གི་བསྟོད་འགྲེལ་སྙིང་གི་ནོར་བུ 10-Segnmentation.txt")
OUTPUT = Path("0-INBOX/temp/tenzin-dhonzang/cleaned.md")

NBT = '༌'       # non-breaking tsheg
STD_TSHEG = '་'  # standard tsheg

# Hand-verified running-header bleed fixes (see docstring above).
HEADER_BLEED_FIXES = [
    (
        "སྐྱུག་མེར་མེར་རམ། ཞེ་སྒྲོལ་མ་ཉེར་གཅིག་གི་བསྟོད་འགྲེལ་སྙིང་གི་ནོར་བུ། མེར་མེར།",
        "སྐྱུག་མེར་མེར་རམ། ཞེ་མེར་མེར།",
    ),
    (
        "མཁའ་འགྲོའི། ནམ་གྲུལ་སྒྲོལ་མ་ཉེར་གཅིག་གི་བསྟོད་འགྲེལ་སྙིང་གི་ནོར་བུ་གྱི། གཤིན་རྗེའི།",
        "མཁའ་འགྲོའི། ནམ་གྲུལ་གྱི། གཤིན་རྗེའི།",
    ),
]


def clean(text: str) -> str:
    stats = {'bom_removed': 0, 'crlf_normalised': 0, 'nbt_replacements': 0,
              'header_bleed_fixes': 0}

    # 1. Strip UTF-8 BOM
    if text.startswith('﻿'):
        text = text[1:]
        stats['bom_removed'] = 1

    # 2. Normalise CRLF -> LF
    stats['crlf_normalised'] = text.count('\r\n')
    text = text.replace('\r\n', '\n')

    # 3. Non-breaking tshegs -> standard tsheg
    stats['nbt_replacements'] = text.count(NBT)
    text = text.replace(NBT, STD_TSHEG)

    # 4. Hand-verified running-header bleed fixes
    for bad, good in HEADER_BLEED_FIXES:
        n = text.count(bad)
        if n:
            text = text.replace(bad, good)
            stats['header_bleed_fixes'] += n

    # 5. Trim trailing whitespace on each line
    text = '\n'.join(l.rstrip() for l in text.split('\n'))

    # 6. Normalise blank lines: collapse runs of 2+ blank lines into exactly one
    text = re.sub(r'\n{3,}', '\n\n', text)

    # 7. Trim leading/trailing blank lines, ensure single trailing newline
    text = text.strip('\n') + '\n'

    print(f"Done — BOM stripped: {stats['bom_removed']}, "
          f"CRLF pairs normalised: {stats['crlf_normalised']}, "
          f"NBT replacements: {stats['nbt_replacements']}, "
          f"header-bleed fixes: {stats['header_bleed_fixes']}")
    return text


if __name__ == '__main__':
    raw = SOURCE.read_text(encoding='utf-8')
    cleaned = clean(raw)
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(cleaned, encoding='utf-8')
    print(f"Written to: {OUTPUT}")
