#!/usr/bin/env python3
"""
clean-taranatha.py
Generated by the clean-raw-text skill (invoked from raw-to-sources).
Removes mechanical OCR/encoding debris from:
  0-INBOX/raw-data/སྒྲོལ་མ་ཉེར་གཅིག/RAC634AC6 ཕྱག་འཚལ་ཉེར་གཅིག་གི་བསྟོད་པའི་རྣམ་པར་བཤད་པ། -Segmentation.txt
Output:
  0-INBOX/temp/taranatha/cleaned.md

Profile findings (see conversation record):
  - page_markers: 0
  - running_headers: 0 (no line repeats >5 times)
  - zero_width_spaces (U+200B): 308 — encoding artifact, stripped
  - BOM (U+FEFF): 1, at file start — stripped
  - non_breaking_tshegs (U+0F0C): 0
  - genuine mid-word space: 1, line 144 "བསྒྲ གས་པས" -> "བསྒྲགས་པས"
    (all other space-between-Tibetan-chars matches are ordinary post-shad
    sentence spacing or spacing inside a transliterated Sanskrit mantra —
    left untouched, not mid-word breaks)
  - orphaned line fragments: none found
  - blank-line runs: paragraphs are separated by double blank lines throughout;
    normalised to a single blank line per the output-format spec
"""
import re
from pathlib import Path

SOURCE = Path("0-INBOX/raw-data/སྒྲོལ་མ་ཉེར་གཅིག/RAC634AC6 ཕྱག་འཚལ་ཉེར་གཅིག་གི་བསྟོད་པའི་རྣམ་པར་བཤད་པ། -Segmentation.txt")
OUTPUT = Path("0-INBOX/temp/taranatha/cleaned.md")

ZWSP = '​'  # zero width space
BOM  = '﻿'  # zero width no-break space / BOM

# One targeted fix: a stray space splitting a single word in half.
# Verified by hand against surrounding context (line 144 of the raw file):
# "...འཇིགས་པའི་སྒྲ་བསྒྲ གས་པས་ས་འོག..." -> "...སྒྲ་བསྒྲགས་པས་ས་འོག..."
MID_WORD_FIXES = [
    ("སྒྲ་བསྒྲ གས་པས", "སྒྲ་བསྒྲགས་པས"),
]


def clean(text: str) -> str:
    stats = {'bom': 0, 'zwsp': 0, 'mid_word_fixes': 0, 'blank_run_collapses': 0}

    if text.startswith(BOM):
        text = text[1:]
        stats['bom'] += 1

    stats['zwsp'] = text.count(ZWSP)
    text = text.replace(ZWSP, '')

    for bad, good in MID_WORD_FIXES:
        n = text.count(bad)
        if n:
            text = text.replace(bad, good)
            stats['mid_word_fixes'] += n

    # Normalise blank lines: collapse runs of 2+ blank lines into exactly one.
    before = text
    text = re.sub(r'\n{3,}', '\n\n', text)
    stats['blank_run_collapses'] = before.count('\n\n\n')

    # Trim leading/trailing blank lines, ensure single trailing newline.
    text = text.strip('\n') + '\n'

    print(f"Done — BOM stripped: {stats['bom']}, ZWSP removed: {stats['zwsp']}, "
          f"mid-word space fixes: {stats['mid_word_fixes']}, "
          f"blank-line runs collapsed: {stats['blank_run_collapses']}")
    return text


if __name__ == '__main__':
    raw = SOURCE.read_text(encoding='utf-8')
    cleaned = clean(raw)
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(cleaned, encoding='utf-8')
    print(f"Written to: {OUTPUT}")
