#!/usr/bin/env python3
"""
clean-sungrab-tulku.py
Generated by the clean-raw-text skill (invoked from raw-to-sources).
Removes mechanical OCR/PDF debris from:
  0-INBOX/raw-data/སྒྲོལ་མ་ཉེར་གཅིག/R1F6AA6C0 སྒྲོལ་མཉེར་གཅིག་གི་རྣམ་བཤད། -Segmentation.txt
Output:
  0-INBOX/temp/sungrab-tulku/work/cleaned.md

Profile findings (see conversation record):
  - page_markers: 0
  - running_headers/footers: none (the 30x repeat of "ཞེས་པ་སྟེ།" is a
    substantive structural transition phrase used throughout this
    word-by-word commentary genre, not a page header/footer -- left as-is)
  - non_breaking_tshegs (U+0F0C): 44 -- replaced with standard tsheg (U+0F0B)
  - mid_word_spaces: no clear PDF-justification artifacts found; the
    space-then-Tibetan-char matches are all legitimate (space after a shad,
    mantra transliteration spacing, date formatting) -- left as-is
  - orphaned_line_fragments: the short "ཞེས་པ་སྟེ།" / "ཞེས་པ་ནི།" lines are
    intentional one-line structural markers (root-quote -> "thus it says" ->
    commentary), not broken fragments -- left as-is
  - double tsheg (1 occurrence, line 9): ambiguous, not one of the
    mechanically-defined categories -- left as-is, flagged for human review
  - original segmentation numbers (1, 2, 3 ... 47) preceding commentary
    units: preserved as-is per raw-to-sources SKILL.md (unsegmented body)
"""
import re
from pathlib import Path

SOURCE = Path("0-INBOX/raw-data/སྒྲོལ་མ་ཉེར་གཅིག/R1F6AA6C0 སྒྲོལ་མཉེར་གཅིག་གི་རྣམ་བཤད། -Segmentation.txt")
OUTPUT = Path("0-INBOX/temp/sungrab-tulku/work/cleaned.md")

NBT = '༌'      # ༌ non-breaking tsheg
STD_TSHEG = '་'  # ་ standard tsheg


def clean(text: str) -> str:
    stats = {'nbt_replacements': 0, 'bom_stripped': 0}

    # 0. Strip a leading UTF-8 BOM if present (mechanical encoding artifact)
    if text.startswith('﻿'):
        text = text.lstrip('﻿')
        stats['bom_stripped'] = 1

    # 1. Non-breaking tshegs -> standard tsheg
    stats['nbt_replacements'] = text.count(NBT)
    text = text.replace(NBT, STD_TSHEG)

    # 2. Normalise blank lines: collapse runs of 3+ newlines to exactly one blank line
    text = re.sub(r'\n{3,}', '\n\n', text)

    # 3. Strip trailing whitespace on each line (mechanical, no content change)
    lines = [l.rstrip() for l in text.split('\n')]
    text = '\n'.join(lines)

    print(f"Done — BOM stripped: {stats['bom_stripped']}, NBT replacements: {stats['nbt_replacements']}")
    return text


if __name__ == '__main__':
    text = SOURCE.read_text(encoding='utf-8')
    cleaned = clean(text)
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(cleaned, encoding='utf-8')
    print(f"Written to: {OUTPUT}")
