#!/usr/bin/env python3
"""
clean-gendun-drub.py
Generated by the clean-raw-text skill.
Removes mechanical debris (UTF-8 BOM, fused page-number artifacts) from:
  0-INBOX/raw-data/སྒྲོལ་མ་ཉེར་གཅིག/རྒྱལ་བ་དགེ་འདུན་གྲུབ་ཀྱི་སྒྲོལ་མའི་འགྲེལ་པ།.docx.txt
Output:
  0-INBOX/temp/gendun-drub/cleaned.md
"""
import re
from pathlib import Path

SOURCE = Path("/Users/tashitsering/Desktop/work/Obsidian/21-taras-rails/0-INBOX/raw-data/སྒྲོལ་མ་ཉེར་གཅིག/རྒྱལ་བ་དགེ་འདུན་གྲུབ་ཀྱི་སྒྲོལ་མའི་འགྲེལ་པ།.docx.txt")
OUTPUT = Path("/Users/tashitsering/Desktop/work/Obsidian/21-taras-rails/0-INBOX/temp/gendun-drub/cleaned.md")

# Bare page-number artifacts fused onto the start of a continuation line,
# each immediately preceded by a blank (single-space) marker line.
# These are print-page breaks landing mid-paragraph (paragraph 23); the
# text before and after each break is a single continuous sentence flow.
PAGE_NUM_LINE = re.compile(r'^(\d{1,3})\s+(?=[ༀ-࿿])')

def clean(text: str) -> str:
    # Strip UTF-8 BOM if present
    text = text.lstrip('﻿')

    lines = text.split('\n')
    out = []
    stats = {'bom_stripped': 1 if '﻿' in text[:1] else 0,
             'page_number_artifacts_removed': 0,
             'blank_marker_lines_removed': 0}

    i = 0
    while i < len(lines):
        line = lines[i]
        stripped = line.strip()

        # Blank marker line (contains only whitespace) immediately followed
        # by a fused page-number line -> drop the blank line and strip the
        # bare page number off the front of the next line. The next line's
        # text is otherwise left exactly as in the source (no rejoining —
        # resegmentation is a separate later step, not this skill's job).
        if stripped == '' and i + 1 < len(lines) and PAGE_NUM_LINE.match(lines[i + 1]):
            stats['blank_marker_lines_removed'] += 1
            next_line = PAGE_NUM_LINE.sub('', lines[i + 1])
            stats['page_number_artifacts_removed'] += 1
            out.append(next_line)
            i += 2
            continue

        out.append(line)
        i += 1

    result = '\n'.join(out)
    # Normalise any accidental run of blank lines
    result = re.sub(r'\n{3,}', '\n\n', result)

    print(f"Done — BOM stripped: {stats['bom_stripped']}, "
          f"page-number artifacts removed: {stats['page_number_artifacts_removed']}, "
          f"blank marker lines removed: {stats['blank_marker_lines_removed']}")
    return result

if __name__ == '__main__':
    text = SOURCE.read_text(encoding='utf-8-sig')
    cleaned = clean(text)
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(cleaned, encoding='utf-8')
    print(f"Written to: {OUTPUT}")
