#!/usr/bin/env python3
"""
clean-lobsang-dawa.py
Generated by the clean-raw-text skill.
Removes mechanical OCR/segmentation debris from:
  0-INBOX/raw-data/སྒྲོལ་མ་ཉེར་གཅིག/R5040C72C སྒྲོལ་མ་ཕྱག་འཚལ་ཉེར་གཅིག་གི་མཆན་འགྲེལ་བཞུགས་སོ།11-sengmentation.txt
Output:
  0-INBOX/temp/lobsang-dawa/work/cleaned.md
"""
import re
from pathlib import Path

SOURCE = Path("0-INBOX/raw-data/སྒྲོལ་མ་ཉེར་གཅིག/R5040C72C སྒྲོལ་མ་ཕྱག་འཚལ་ཉེར་གཅིག་གི་མཆན་འགྲེལ་བཞུགས་སོ།11-sengmentation.txt")
OUTPUT = Path("0-INBOX/temp/lobsang-dawa/work/cleaned.md")

NBT = '༌'  # non-breaking tsheg
STD_TSHEG = '་'  # standard tsheg

def clean(text: str) -> str:
    stats = {'nbt_replacements': 0, 'doubled_tsheg_fixes': 0}

    # 1. Non-breaking tshegs -> standard tsheg
    stats['nbt_replacements'] = text.count(NBT)
    text = text.replace(NBT, STD_TSHEG)

    # 2. Doubled standard tshegs (literal duplicate punctuation, e.g. "བ་་ཐུགས")
    text, n = re.subn(STD_TSHEG + '{2,}', STD_TSHEG, text)
    stats['doubled_tsheg_fixes'] = n

    # 3. Normalise blank lines (collapse runs of 3+ newlines to a single blank line)
    text = re.sub(r'\n{3,}', '\n\n', text)

    print(f"Done — NBT replacements: {stats['nbt_replacements']}, "
          f"doubled-tsheg fixes: {stats['doubled_tsheg_fixes']}")
    return text

if __name__ == '__main__':
    text = SOURCE.read_text(encoding='utf-8')
    cleaned = clean(text)
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(cleaned, encoding='utf-8')
    print(f"Written to: {OUTPUT}")
