#!/usr/bin/env python3
"""
clean-R46BA3ACB.py
Generated by the clean-raw-text skill.
Removes mechanical OCR/PDF debris from:
  0-INBOX/raw-data/སྒྲོལ་མ་ཉེར་གཅིག/R46BA3ACB ༄༅། །སྒྲོལ་མར་ཕྱག་འཚལ་ཉེར་གཅིག་གིས་བསྟོད་པའི་རྣམ་བཤད་ཡིད་འཕྲོག་ཨུཏྤལའི་ཆུན་པོ་ཞེས་བྱ་བ་བཞུགས་སོ། །-segmentation.txt
Output:
  0-INBOX/temp/R46BA3ACB/cleaned.md

Profile findings (see conversation record):
  - page_markers: 0
  - running_headers: 0 substantive-free repeats (the one repeated line,
    "ཞེས་པ་སྟེ།" x21, is the commentary's own recurring phrase introducing
    each verse quotation — substantive text, not a page header/footer — left untouched)
  - mid_word_spaces: 0 genuine (2 raw regex hits were both spaces inside
    quoted mantra strings after a visarga ཿ, not OCR-inserted breaks —
    left untouched)
  - non_breaking_tshegs (U+0F0C ༌): 36
  - orphaned_line_fragments: 0
"""
import re
from pathlib import Path

SOURCE = Path("0-INBOX/raw-data/སྒྲོལ་མ་ཉེར་གཅིག/R46BA3ACB ༄༅། །སྒྲོལ་མར་ཕྱག་འཚལ་ཉེར་གཅིག་གིས་བསྟོད་པའི་རྣམ་བཤད་ཡིད་འཕྲོག་ཨུཏྤལའི་ཆུན་པོ་ཞེས་བྱ་བ་བཞུགས་སོ། །-segmentation.txt")
OUTPUT = Path("0-INBOX/temp/R46BA3ACB/cleaned.md")

NBT = '༌'       # non-breaking tsheg
STD_TSHEG = '་'  # standard tsheg

def clean(text: str) -> str:
    stats = {'nbt_replacements': 0}

    nbt_count = text.count(NBT)
    text = text.replace(NBT, STD_TSHEG)
    stats['nbt_replacements'] = nbt_count

    # Normalise blank lines: collapse runs of 3+ newlines into a single blank line
    result = re.sub(r'\n{3,}', '\n\n', text)
    # Trim trailing whitespace at end of file
    result = result.strip('\n') + '\n'

    print(f"Done — NBT replacements: {stats['nbt_replacements']}")
    return result

if __name__ == '__main__':
    text = SOURCE.read_text(encoding='utf-8')
    cleaned = clean(text)
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(cleaned, encoding='utf-8')
    print(f"Written to: {OUTPUT}")
